### ISSUE TITLE
Why do you think this is "Material Design". Only for shadows?

### ISSUE THREAD

**Issue by equinusocio** [melnik909/material_bootstrap_theme#2]
Please remove "material design" words from this project..

**Comment by melnik909** [comment]
What in your opinion isn't correct?

**Comment by equinusocio** [comment]
Almost all... you followed MD Guidelines?

**Comment by meyacine** [comment]
This is just responsive design. A bootstrap modified skin. Please refer to Google Material Design guidelines.

**Comment by equinusocio** [comment]
:+1:

**Comment by melnik909** [comment]
Thanks for comments. You can tell, what not so with this skin? (except buttons) I wanted to make MD as I see

**Comment by meyacine** [comment]
Here are some implementations of MD  https://material.angularjs.org or http://materializecss.com/. If you're on lolipop you can see color scheme for status bar, toolbar and the NavigationDrawer (Java native terms) known as navbar etc. Your project is very interessant, god job and good luck.
