### ISSUE TITLE
Material design без переписования классов

### ISSUE THREAD

**Issue by AbuLoot** [melnik909/material_bootstrap_theme#7]
Былобы удобна подключить material bootstrap theme к сущесвующему проекту и получить в результате material design, без переписовании классов для сохранении времени. Как это сделано в bootswatch.com. Для того чтобы css был легким думаю просто стоит кастоматизировать bootstrap.

**Comment by melnik909** [comment]
У меня есть два вопроса. Как при таком варианте будет производится откат версии или обновление на новую версию Bootstrap'а? И если вам понравится другой skin, то как будете переходить на него? 

При текущей реализации перечисленные проблемы решаются простым отключением файла и удалением классов.

**Comment by AbuLoot** [comment]
Навыков у меня не хватает чтобы ответить на Ваши вопросы. Мне просто удобен тот вариант который реализован в bootswatch. Насчет моего последнего предложения, то я думаю они (bootswatch) так и делают потомучто когда обновленяется bootstrap у них все версии themes тоже обновляются. Складывается впечатление что все это автоматизировано.
